language: go

go:
  - 1.8.3
env:

before_install:
  - ls
install:
  - go get -v -u github.com/tinycedar/classp/classfile
  - cd $GOPATH/src/github.com/tinycedar/vanilla
  - go build
  - ./vanilla test.MathTest
before_script:

after_script:

script: